### ISSUE TITLE
Everything live/reactive

### ISSUE THREAD

**Issue by dumblob** [Tablam/TablaM#47]
I wonder whether every single data "cell" (or shall I say "value"?) will be "live" by default? I mean imagine having such a "cell" and then N+ processes/threads/tasks/fibers/younameit **writing** non-stop to this cell but in parallel there will be M+ readers reading from it. Will every single write immediately appear to readers (in the sense of "nudging" them to see the new value)?

**Comment by dumblob** [comment]
Fundamentally this has nothing to do with async/parallelism (even though paralellelism and/or async stuff is one of the ways to implement this).

So my question stands :wink:.

Else how would you want to achieve data-orientation if there a change to a cell/value will not propagate to readers?

**Comment by mamcx** [comment]
> even though paralellelism and/or async stuff is one of the ways to implement this
Yeah, sure!.

I'm looking for a small set of common paradigms that could solve several use-cases, so any chance of this need to be on top of that...

> Else how would you want to achieve data-orientation if a change to a cell/value will not propagate to readers?

That is a _kind_ of data orientation, alike was with http://witheve.com. Having some support for this could be neat (a better way to do "triggers"), but I think that will be among the lines of have an actor system or channels like in go, instead of something fundamental to the lang.

P.D: In https://www.reddit.com/r/ProgrammingLanguages/ is a good place to get a better response about deep stuff like this. I'm open to ideas, as I said, not yet settled on how exactly to deal with the fundamental task of making operations concurrent/parallel, and I'm looking for something relatively easy to implement AND for the end-user to understand.

**Comment by dumblob** [comment]
Ah, ok. I see you are not convinced that such kind of "liveliness/reactiveness" belongs to the "small set of common paradigms" to build upon.

And that is OK (despite me being convinced it is the other way around :wink:).

(feel free to ping me to discuss async/parallelism/concurrency/reactiveness/you_name_it as I have spent already too many years with this topic as you can see e.g. on GitHub in hundreds of discussions in different projects :wink:)
